### ISSUE TITLE
copyToTemp() mkdirSync bug, should add recursive: true

### ISSUE THREAD

**Issue by SteveCruise** [bencevans/screenshot-desktop#271]
should add recursive: true
`fs.mkdirSync(path.join(os.tmpdir(), 'screenCapture'), {recursive: true})`

**Comment by pablohpsilva** [comment]
The following function dies if a screenshot was already taken. I suggest overwriting it or simply deleting before creating an image there. Also, a random name can be used.
```
function copyToTemp () {
  const tmpBat = path.join(os.tmpdir(), 'screenCapture', 'screenCapture_1.3.2.bat')
  const tmpManifest = path.join(os.tmpdir(), 'screenCapture', 'app.manifest')
  const includeBat = path.join(__dirname, 'screenCapture_1.3.2.bat').replace('app.asar', 'app.asar.unpacked')
  const includeManifest = path.join(__dirname, 'app.manifest').replace('app.asar', 'app.asar.unpacked')
  if (!fs.existsSync(tmpBat)) {
    fs.mkdirSync(path.join(os.tmpdir(), 'screenCapture'))
    const sourceData = {
      bat: fs.readFileSync(includeBat),
      manifest: fs.readFileSync(includeManifest)
    }
    fs.writeFileSync(tmpBat, sourceData.bat)
    fs.writeFileSync(tmpManifest, sourceData.manifest)
  }
  return tmpBat
}
```

**Comment by pablohpsilva** [comment]
```
Error occurred in handler for 'smallAreaScreenShot': Error: ENOENT: no such file or directory, open 'C:\Users\admin\Documents\BoTibia\.webpack\main\screenCapture_1.3.2.bat'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at copyToTemp (C:\Users\admin\Documents\BoTibia\.webpack\main\index.js:56790:15)
    at C:\Users\admin\Documents\BoTibia\.webpack\main\index.js:56810:20
    at new Promise (<anonymous>)
    at windowsSnapshot (C:\Users\admin\Documents\BoTibia\.webpack\main\index.js:56800:10)
    at $c550fd30f5174fcd$export$ed45beb1e325e9b (C:\Users\admin\Documents\BoTibia\.webpack\main\index.js:19138:74)   
    at C:\Users\admin\Documents\BoTibia\.webpack\main\index.js:74228:72 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\admin\\Documents\\BoTibia\\.webpack\\main\\screenCapture_1.3.2.bat'
}
```
