### ISSUE TITLE
EEXIST file already exists

### ISSUE THREAD

**Issue by rufus-codeb** [bencevans/screenshot-desktop#275]
I am using screenshot-desktop in my electron-react app version 24 screenshot function is running fine in development mode but when i made a build of my electron app I am getting this error 

 Error: EEXIST: file already exists, mkdir 'C:\Users\DELL\AppData\Local\Temp\screenCapture'
    at mkdirSync (node:fs:1395:3)
    at t.mkdirSync (node:electron/js2c/asar_bundle:2:12614)
    at copyToTemp (C:\Users\DELL\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\win32\index.js:20:8)
    at C:\Users\DELL\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\win32\index.js:93:20
    at new Promise (<anonymous>)
    at Function.listDisplays (C:\Users\DELL\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\win32\index.js:92:10)
    at C:\Users\DELL\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\utils.js:40:14
    at new Promise (<anonymous>)
    at defaultAll (C:\Users\DELL\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\utils.js:39:10)
    at windowsSnapshot.all (C:\Users\DELL\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\win32\index.js:111:29)

When i tested my app in another pc I got this error

screenshot-error Error: ENOENT: no such file or directory, open 'C:\Users\kpman\AppData\Local\Programs\timelogger-desktop\resources\app.asar.unpacked\node_modules\screenshot-desktop\lib\win32\screenCapture_1.3.2.bat'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at copyToTemp (C:\Users\kpman\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\win32\index.js:22:15)
    at C:\Users\kpman\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\win32\index.js:93:20
    at new Promise (<anonymous>)
    at Function.listDisplays (C:\Users\kpman\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\win32\index.js:92:10)
    at C:\Users\kpman\AppData\Local\Programs\timelogger-desktop\resources\app.asar\node_modules\screenshot-desktop\lib\utils.js:40:14
    at new Promise (<anonymous>)

**Comment by lderrickable** [comment]
I ran into this today and I think it might occur because screenshot-desktop gets interrupted while it is taking a screenshot. There is probably a cleanup phase and if it isn't able to complete, then you end up with a temp file that doesn't get cleaned up. If you delete the file at C:\Users\DELL\AppData\Local\Temp\screenCapture it should start working again.

**Comment by 3IMAD69** [comment]
this solve it for me
